//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothäftet med ID {0} finns inte i databasen..
        /// </summary>
        internal static string BookletDontExistsErrorSwedish {
            get {
                return ResourceManager.GetString("BookletDontExistsErrorSwedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel inträffade när nothäftet skulle raderas från databasen..
        /// </summary>
        internal static string DeleteBookletErrorSwedish {
            get {
                return ResourceManager.GetString("DeleteBookletErrorSwedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothäftet har raderats permanent från databasen..
        /// </summary>
        internal static string DeleteBookletSuccessSwedish {
            get {
                return ResourceManager.GetString("DeleteBookletSuccessSwedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel inträffade när stycket skulle tas bort från innehållslistan..
        /// </summary>
        internal static string DeleteContentRecordErrorSwedish {
            get {
                return ResourceManager.GetString("DeleteContentRecordErrorSwedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stycket har tagits bort från innehållslistan..
        /// </summary>
        internal static string DeleteContentRecordSuccessSwedish {
            get {
                return ResourceManager.GetString("DeleteContentRecordSuccessSwedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting the data..
        /// </summary>
        internal static string DeleteRecordError {
            get {
                return ResourceManager.GetString("DeleteRecordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel intfäffade när sidan skulle laddas..
        /// </summary>
        internal static string GeneralErrorSwedish {
            get {
                return ResourceManager.GetString("GeneralErrorSwedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel inträffade när stycket skulle läggas till i innehållslistan..
        /// </summary>
        internal static string InsertContentRecordErrorSwedish {
            get {
                return ResourceManager.GetString("InsertContentRecordErrorSwedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stycket har lagts till i innehållslistan..
        /// </summary>
        internal static string InsertContentRecordSuccessSwedish {
            get {
                return ResourceManager.GetString("InsertContentRecordSuccessSwedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel inträffade när det nya nothäftet sparades..
        /// </summary>
        internal static string InsertNewBookletErrorSwedish {
            get {
                return ResourceManager.GetString("InsertNewBookletErrorSwedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det nya nothäftet har sparats i databasen..
        /// </summary>
        internal static string InsertNewBookletSuccessSwedish {
            get {
                return ResourceManager.GetString("InsertNewBookletSuccessSwedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while inserting the data..
        /// </summary>
        internal static string InsertRecordError {
            get {
                return ResourceManager.GetString("InsertRecordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste ha minst ett stycke i innehållslistan..
        /// </summary>
        internal static string InsertUpdateBookletNoContentErrorSwedish {
            get {
                return ResourceManager.GetString("InsertUpdateBookletNoContentErrorSwedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving the data..
        /// </summary>
        internal static string SaveDataError {
            get {
                return ResourceManager.GetString("SaveDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel inträffade när nothäftets innehåll skulle hämtas..
        /// </summary>
        internal static string SelectBookletContentRecordsErrorSwedish {
            get {
                return ResourceManager.GetString("SelectBookletContentRecordsErrorSwedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothäfte nummer {0} finns inte i databasen..
        /// </summary>
        internal static string SelectBookletRecordByIDErrorSwedish {
            get {
                return ResourceManager.GetString("SelectBookletRecordByIDErrorSwedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel inträffade när nothäftena hämtades..
        /// </summary>
        internal static string SelectBookletsErrorSwedish {
            get {
                return ResourceManager.GetString("SelectBookletsErrorSwedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel infräffade när musikstycken till dropdown-listan skulle hämtas..
        /// </summary>
        internal static string SelectPiecesToDropDownListErrorSwedish {
            get {
                return ResourceManager.GetString("SelectPiecesToDropDownListErrorSwedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while selecting the data..
        /// </summary>
        internal static string SelectRecordError {
            get {
                return ResourceManager.GetString("SelectRecordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel inträffade när ändringarna skulle sparas..
        /// </summary>
        internal static string UpdateBookletRecordErrorSwedish {
            get {
                return ResourceManager.GetString("UpdateBookletRecordErrorSwedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändringarna har sparats..
        /// </summary>
        internal static string UpdateBookletRecordSuccessSwedish {
            get {
                return ResourceManager.GetString("UpdateBookletRecordSuccessSwedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the data..
        /// </summary>
        internal static string UpdateRecordError {
            get {
                return ResourceManager.GetString("UpdateRecordError", resourceCulture);
            }
        }
    }
}
